modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="industrial_economy"
version="1.0.0"
displayName="IndustrialEconomy"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="dZ"

[[dependencies.industrial_economy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




